image:
  file: .gitpod.Dockerfile
tasks:
  - name: Requirements
    init: |
      pre-commit install
      pip3 install -r requirements_test.txt
ports:
  - port: 9123
    onOpen: notify
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: false
vscode:
  extensions:
    - esbenp.prettier-vscode
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - ms-python.python
