name: Bug Report
description: Create a report to help us improve the integration
labels: [bug]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Did you read the instructions?
      description: We have a high load of issue reports, thus we would like to ask you to read a few instructions first.
      options:
        - label: I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.
          required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is. What did you expect to happen?

  - type: markdown
    attributes:
      value: |
        ## Environment

  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What version of this integration (ha-tahoma) has the issue?
      placeholder: 2.5.0
      description: >
        Can be found in the Configuration panel -> Info.

  - type: input
    id: ha_version
    validations:
      required: true
    attributes:
      label: What version of Home Assistant Core has the issue?
      placeholder: core-
      description: >
        Can be found in the Configuration panel -> Info.

  - type: markdown
    attributes:
      value: |
        ## Device

  - type: input
    id: overkiz_hub
    validations:
      required: true
    attributes:
      label: Which gateway / hub do you use?
      placeholder: e.g. Somfy TaHoma or Cozytouch
      description: >
        Can be found in the Configuration panel -> Integrations -> Somfy TaHoma -> (x) devices

  - type: input
    id: overkiz_device_model
    validations:
      required: true
    attributes:
      label: Device model
      placeholder: e.g. PositionableScreen
      description: >
        Can be found in the Configuration panel -> Integrations -> Somfy TaHoma -> (x) devices -> Model.

  - type: input
    id: overkiz_device_type
    validations:
      required: true
    attributes:
      label: Device type
      placeholder: e.g. io:DimmableLightIOComponent
      description: >
        Can be found in the Configuration panel -> Integrations -> Somfy TaHoma -> (x) devices. Click on the device and copy the firmware.

  - type: markdown
    attributes:
      value: |
        ## Details

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: If you have any additional information for us, use the field below. Please note, you can attach screenshots or screen recordings here, by dragging and dropping files in the field below.

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
