blank_issues_enabled: false
contact_links:
  - name: Home Assistant Community forum
    url: https://community.home-assistant.io/t/tahoma-integration-refactored/202025/last
    about: Please ask and answer questions here.
