cover_my:
  description: Move cover to preset position, simulating the "my" button.
  fields:
    entity_id:
      description: Name of entity that will be set to preset position.
      example: "cover.living_room"

light_my:
  description: Move light to preset position, simulating the "my" button.
  fields:
    entity_id:
      description: Name of entity that will be set to preset position.
      example: "light.living_room"

execute_command:
  description: Send a command to tahomalink endpoint through the API.
  fields:
    entity_id:
      description: Name of entity that will be set to preset position.
      example: "light.living_room"
    command:
      description: Command to send
      example: "setIntensity"
    args:
      description: List of arguments to pass to the command if necessary
      example: 100