name: Linters (flake8, black, isort)

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-python@v3.1.4
      - uses: pre-commit/action@v3.0.0
